# AI 提示词示例

本文档基于 [AI 3D Studio 官方手册](https://github.com/raydeleu/AI3DStudioManual)，提供了有效的 AI 提示词示例，帮助你更好地使用 AI 生成 3D 模型。

## 📝 基础形状

### 简单几何体

```
创建一个边长为50的立方体
```

```
生成一个半径为30的球体
```

```
创建一个底面半径20，高度100的圆柱体
```

```
生成一个底面半径30，顶面半径10，高度80的圆锥
```

## 🔧 组合形状

### 布尔运算

```
创建一个边长100的立方体，中间挖一个半径30的球形孔
```

```
生成两个相交的圆柱体，形成十字形状，每个圆柱体半径20，长度100
```

```
创建三个球体的并集，半径都是30，位置分别在(0,0,0)、(50,0,0)、(25,43,0)
```

```
创建一个立方体(100x100x50)，从中减去一个圆柱体(半径25，高度60)
```

### 多重布尔运算

```
创建一个长方体(150x100x30)，在四个角各挖一个圆柱形孔(半径10，贯穿)
```

```
生成一个球体(半径50)，从六个方向各挖一个圆柱形孔(半径15)，形成镂空球
```

## 🎨 复杂模型

### 2D 轮廓拉伸

```
创建一个五角星形状的 2D 轮廓，然后拉伸 20mm 形成 3D 实体
```

```
绘制一个圆角矩形(100x60，圆角半径10)，拉伸高度 30mm
```

```
创建一个 L 形截面，宽度 50mm，厚度 10mm，拉伸高度 100mm
```

### 旋转拉伸（Revolve）

```
创建一个梯形截面，绕 Z 轴旋转 360 度形成碗状物体
```

```
绘制一个半圆形轮廓，旋转 180 度形成球体
```

```
创建一个瓶子：绘制瓶子的半边轮廓，然后绕中心轴旋转 360 度
```

### 放样（Loft）

```
创建两个圆形截面，底部半径 50，顶部半径 30，用放样连接形成圆台
```

```
生成三个不同大小的正方形截面，从下到上依次为 60x60、40x40、20x20，用放样连接
```

### 机械零件

```
创建一个简单的齿轮：外径 100，内径 40，厚度 20，齿数 20
```

```
生成一个法兰盘：外径 150，内径 60，厚度 20，带 6 个螺栓孔（直径 10，分布在直径 110 的圆周上）
```

```
创建一个轴承座：底座尺寸 200x150x30，中心有直径 80 的圆孔，四角有直径 12 的安装孔
```

```
设计一个简单的轴：主体直径 30，长度 150，两端各有一段直径 20、长度 25 的细轴
```

### 建筑元素

```
创建一个简单的房屋模型：底座 100x100x5，墙体 100x100x80（壁厚 10），带三角形屋顶（高度 50）
```

```
生成一个楼梯：10 级台阶，每级宽 100，深 30，高 15
```

```
创建一个拱门：宽度 100，高度 150，厚度 20，拱形顶部
```

```
设计一个柱子：底座 40x40x10，柱身直径 30、高度 200，柱头 40x40x15
```

### 日常物品

```
创建一个咖啡杯：底部直径 60，顶部直径 80，高度 100，壁厚 3，带把手
```

```
生成一个花瓶：使用旋转拉伸，底部直径 50，中间直径 80，顶部直径 60，高度 150
```

```
创建一个简单的椅子：座面 50x50x5，高度 45，靠背 50x5x80，四条腿直径 5、高度 45
```

```
设计一个笔筒：圆柱形，外径 80，内径 75，高度 100，底部封闭
```

```
创建一个简单的碗：使用旋转拉伸，外径 120，内径 110，高度 50，底部厚度 5
```

```
生成一个手机支架：底座 100x80x10，支撑臂倾斜 60 度、高度 80，顶部有宽度 70、深度 10 的手机槽
```

## 🎯 参数化模型

### 带滑块控制

```
创建一个可调节半径的球体，半径范围 10-50，默认 30
```

```
生成一个可调节孔径的立方体，立方体边长 100，孔径范围 10-40，默认 25
```

```
创建一个参数化的圆柱体，可以调节半径(10-50，默认 30)和高度(50-200，默认 100)
```

```
设计一个参数化齿轮：外径可调(80-120)，内径可调(30-50)，厚度可调(10-30)
```

### 带复选框控制

```
创建一个立方体(边长 100)，用复选框控制是否在中心挖孔(孔径 30)
```

```
生成一个圆柱体(半径 40，高度 100)，用复选框控制是否添加圆角(半径 5)
```

### 多参数组合

```
创建一个参数化的盒子：
- 长度滑块(50-200，默认 100)
- 宽度滑块(50-200，默认 80)
- 高度滑块(20-100，默认 50)
- 壁厚滑块(2-10，默认 5)
- 是否添加盖子(复选框，默认 true)
```

## 💡 高级技巧

### 使用变换

```
创建 5 个球体(半径 20)，沿 X 轴等间距排列，间距 50
```

```
生成一个立方体阵列：3x3x3，每个立方体边长 20，间距 10
```

```
创建一个圆形阵列：12 个立方体(边长 15)围成一圈，半径 100
```

```
创建一个螺旋阵列：10 个球体(半径 10)沿螺旋线排列，每圈上升 20
```

### 镜像和对称

```
创建一个 L 形物体，然后镜像形成对称的 U 形
```

```
生成一个半圆柱体，然后沿 XZ 平面镜像形成完整圆柱
```

```
创建一个四分之一圆环，通过两次镜像形成完整圆环
```

### 使用高级操作

```
创建一个圆形截面(半径 10)，沿贝塞尔曲线路径扫掠形成弯曲的管道
```

```
生成一个五角星截面，旋转拉伸 360 度形成星形实体
```

```
创建两个不同大小的圆形截面(底部半径 50，顶部半径 30)，用放样连接形成渐变形状
```

```
绘制一个矩形轮廓(100x60)，向外偏移 10mm，然后拉伸形成带凸缘的形状
```

### 使用圆角和倒角

```
创建一个立方体(边长 100)，所有边都带 5mm 圆角
```

```
生成一个长方体(150x100x50)，顶部边缘倒角 3mm，底部边缘圆角 5mm
```

```
创建一个圆柱体(半径 40，高度 100)，顶部和底部边缘圆角 5mm
```

```
设计一个立方体(边长 80)，只对顶面的四条边添加 10mm 圆角
```

### 文字和标记

```
创建 3D 文字 "HELLO"，字体大小 36，厚度 10，字体 Consolas
```

```
生成一个名牌：底板 150x50x5，上面有凸起的 3D 文字 "NAME"(高度 3)
```

```
创建一个立方体(边长 100)，在顶面刻上凹陷的文字 "TOP"(深度 2)
```

## 📋 提示词编写技巧

### ✅ 好的提示词特征

1. **明确具体** - 提供准确的尺寸和参数
   - ✅ "创建一个边长 50 的立方体"
   - ❌ "创建一个立方体"

2. **结构清晰** - 按逻辑顺序描述
   - ✅ "创建一个底座 100x100x20，上面放一个半径 30 的球体"
   - ❌ "球体和底座，球体半径 30，底座 100x100x20"

3. **使用专业术语** - 使用 CAD 相关术语
   - ✅ "创建一个圆柱体，底面半径 20，高度 100"
   - ❌ "创建一个圆的长条"

4. **分步描述** - 复杂模型分步骤描述
   - ✅ "首先创建一个立方体(边长 100)，然后在中心挖一个圆柱形孔(半径 25)，最后给所有边添加 5mm 圆角"
   - ❌ "创建一个带孔和圆角的立方体"

5. **指定坐标系** - 明确方向和位置
   - ✅ "创建两个圆柱体，一个沿 Z 轴，一个沿 X 轴，在原点相交"
   - ❌ "创建两个相交的圆柱体"

6. **说明布尔运算** - 明确是并集、差集还是交集
   - ✅ "创建一个立方体，从中减去一个球体"
   - ❌ "创建一个立方体和球体的组合"

### ❌ 避免的问题

1. **过于模糊** - "创建一个好看的模型"
2. **缺少尺寸** - "创建一个大立方体"
3. **过于复杂** - 一次性描述太多细节（建议分步骤）
4. **不切实际** - "创建一辆完整的汽车"（太复杂，建议简化）
5. **单位不明** - "创建一个半径 5 的球"（应说明单位，默认 mm）
6. **方向不清** - "旋转 90 度"（应说明绕哪个轴）

### 💡 提示词优化示例

**模糊 → 清晰**
- ❌ "创建一个带孔的盒子"
- ✅ "创建一个长方体(100x80x50)，在中心有一个贯穿的圆柱形孔(直径 20)"

**简单 → 参数化**
- ❌ "创建一个半径 30 的球体"
- ✅ "创建一个可调节半径的球体，半径范围 10-50，默认 30"

**单一 → 组合**
- ❌ "创建一个圆柱体"
- ✅ "创建一个圆柱体(半径 40，高度 100)，顶部和底部添加 5mm 圆角"

**平面 → 立体**
- ❌ "创建一个五角星"
- ✅ "创建一个五角星形状的 2D 轮廓，然后拉伸 20mm 形成 3D 实体"

## 🎓 进阶示例

### 参数化设计

```
创建一个参数化的螺栓：
- 头部：六角形，对边距离用滑块控制(10-30，默认 20)
- 杆部：圆柱形，直径 8，长度用滑块控制(20-100，默认 50)
- 螺纹：简化为圆柱形
```

```
设计一个参数化的齿轮：
- 外径滑块(80-150，默认 100)
- 内径滑块(20-60，默认 40)
- 厚度滑块(10-40，默认 20)
- 齿数滑块(12-30，默认 20)
```

### 组合设计

```
创建一个简单的机器人：
- 身体：立方体 40x40x60
- 头部：球体，半径 25，位于身体顶部
- 手臂：两个圆柱体，直径 10，长度 50，从身体两侧伸出
- 腿部：两个圆柱体，直径 12，长度 60，从身体底部向下
```

```
设计一个简单的桌子：
- 桌面：长方体 200x100x10
- 四条腿：圆柱体，直径 8，高度 70，位于四角
- 可选：用复选框控制是否添加横梁加固
```

### 实用零件

```
创建一个手机支架：
- 底座：长方体 100x80x10
- 支撑臂：从底座后部向上倾斜 60 度，高度 80，厚度 10
- 手机槽：在支撑臂顶部，宽度 70，深度 10，高度 15
```

```
设计一个笔筒：
- 外壳：圆柱体，外径 80，内径 75，高度 100
- 底部：圆柱体，直径 80，厚度 5
- 分隔：内部添加十字形分隔板，厚度 3
```

```
创建一个简单的门把手：
- 把手主体：圆柱体，直径 30，长度 120
- 两端球形：半径 20
- 连接座：圆柱体，直径 50，厚度 15，中心有安装孔
```

### 复杂几何

```
创建一个莫比乌斯环：
- 使用矩形截面(宽 20，厚 5)
- 沿圆形路径(半径 100)扫掠
- 扫掠过程中旋转 180 度
```

```
设计一个弹簧：
- 使用圆形截面(直径 5)
- 沿螺旋路径扫掠
- 螺旋半径 30，螺距 15，圈数 10
```

```
创建一个齿轮联动装置：
- 大齿轮：外径 120，齿数 30
- 小齿轮：外径 60，齿数 15
- 两齿轮正确啮合，中心距 90
```

### 建筑模型

```
创建一个简单的亭子：
- 底座：正方形平台 200x200x10
- 四根柱子：圆柱体，直径 20，高度 200，位于四角内侧 30
- 顶部：四角锥形屋顶，底边 200，高度 80
```

```
设计一个拱桥：
- 桥面：长方体 300x100x20
- 拱形支撑：半圆形，跨度 300，厚度 30，高度 100
- 栏杆：两侧各 10 根柱子，高度 50
```

## 💬 获取帮助

如果 AI 生成的结果不理想：

1. **细化描述** - 添加更多细节和尺寸
   - 例如：将"创建一个盒子"改为"创建一个长方体(100x80x50)，壁厚 5mm"

2. **分步生成** - 先生成基础形状，再逐步添加细节
   - 第一步：创建基础形状
   - 第二步：添加孔洞或切割
   - 第三步：添加圆角或倒角

3. **参考示例** - 使用本文档中的示例作为模板
   - 找到类似的示例
   - 修改尺寸和参数

4. **手动调整** - 在生成的代码基础上手动修改
   - 按 F5 刷新预览
   - 使用滑块实时调整参数

5. **简化需求** - 如果模型太复杂，分解为多个简单部分
   - 先创建主体结构
   - 再添加细节装饰

6. **使用正确术语** - 参考下方的 CAD 术语表
   - 使用标准的几何和 CAD 术语
   - 明确指定操作类型（并集、差集、交集等）

## 📚 常用 CAD 术语

### 基础几何
- **立方体/长方体** - Box
- **球体** - Sphere
- **圆柱体** - Cylinder
- **圆锥/圆台** - Cone
- **圆环** - Torus

### 操作类型
- **拉伸** - Extrude（将 2D 轮廓拉伸成 3D）
- **旋转拉伸** - Revolve（绕轴旋转形成 3D）
- **放样** - Loft（连接多个截面）
- **扫掠** - Pipe/Sweep（沿路径扫掠）
- **偏移** - Offset（轮廓向内或向外偏移）

### 布尔运算
- **并集** - Union（合并多个形状）
- **差集** - Difference（从一个形状中减去另一个）
- **交集** - Intersection（保留重叠部分）

### 边缘处理
- **圆角** - Fillet（边缘变圆滑）
- **倒角** - Chamfer（边缘切角）

### 变换
- **平移** - Translate（移动位置）
- **旋转** - Rotate（绕轴旋转）
- **缩放** - Scale（改变大小）
- **镜像** - Mirror（对称复制）

### 阵列
- **线性阵列** - 沿直线方向重复
- **圆形阵列** - 绕圆周重复
- **矩阵阵列** - 在平面上按网格重复

## 🔗 相关资源

- [AI 3D Studio 官方手册](https://github.com/raydeleu/AI3DStudioManual) - 完整的 API 文档和教程
- [AI 3D Studio 函数文档](README_CN.md#-支持的-cad-函数) - 本项目支持的函数列表
- [配置说明](SETUP.md) - 环境配置和部署指南
- [项目主页](README_CN.md) - 项目介绍和快速开始

## 🎯 快速参考

### 最常用的提示词模板

**基础形状**
```
创建一个[形状名称]，[尺寸参数]
```

**带孔的形状**
```
创建一个[基础形状]([尺寸])，在[位置]挖一个[孔形状]([孔尺寸])
```

**参数化模型**
```
创建一个可调节的[形状]，[参数名]范围[最小值]-[最大值]，默认[默认值]
```

**组合模型**
```
创建一个[模型名称]：
- [部件1]：[形状]([尺寸])
- [部件2]：[形状]([尺寸])，位于[位置]
- [部件3]：[形状]([尺寸])，[其他说明]
```

**带圆角的形状**
```
创建一个[形状]([尺寸])，[边缘位置]添加[半径]圆角
```

---

**提示**: 开始时使用简单的提示词，逐步增加复杂度，这样可以更好地理解 AI 的能力范围。如果一次生成失败，尝试简化描述或分步骤生成。
